apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta-dep-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp-container-name
          image: testapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000