apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: my-namespace      
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      nodeSelector:             
        kubernetes.io/hostname: minikube   
      containers:
        - name: testapp
          image: testapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
